environment:
  jail:
    version: "14.2-RELEASE"
    arch: "amd64"

  make.conf: |
    #OPTIONS_SET+= LZ4 LZO LZO2 LZMA ZLIB ZSTD BROTLI

packages:
  - name: "www/nginx"
    options: |
      #OPTIONS_FILE_SET+=HTTP_SSL
