name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        env:
          GOOS: freebsd
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -o poudrage-freebsd-amd64 cmd/poudrage/main.go
          chmod +x poudrage-freebsd-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: poudrage-freebsd-amd64
          generate_release_notes: true
